[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-3.0",
]
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = [
    { name = "openssl" },
]

[advisories]
ignore = [
    "RUSTSEC-2024-0388",
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
