#!/bin/bash
# Simple coverage report generator

set -e

echo "Generating simple coverage report..."

# Ensure reports directory exists
mkdir -p reports

# Run coverage and capture output
echo "Running cargo llvm-cov..."
cargo llvm-cov --all-features --workspace 2>/dev/null | tee target/coverage-output.txt

# Extract coverage percentage
COVERAGE_PCT=$(grep -E "TOTAL.*%" target/coverage-output.txt | tail -1 | awk '{for(i=1;i<=NF;i++) if($i ~ /%$/) print $i}' | sed 's/%//' | head -1)

if [[ -z "$COVERAGE_PCT" ]]; then
    COVERAGE_PCT="0"
fi

# Generate simple markdown report
cat > reports/coverage-report.md << EOF
# Coverage Report

> Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")  
> Branch: \`$(git branch --show-current 2>/dev/null || echo "unknown")\`  

## Summary

![Coverage Badge](https://img.shields.io/badge/coverage-${COVERAGE_PCT}%25-brightgreen)

**Overall Coverage: ${COVERAGE_PCT}%**

## Raw Coverage Output

\`\`\`
$(cat target/coverage-output.txt)
\`\`\`

---

*Generated by cargo-llvm-cov*
EOF

echo "✅ Coverage report saved to reports/coverage-report.md"
echo "   Coverage: ${COVERAGE_PCT}%"